#ENC[AES256_GCM,data:NUOUdJCc/7TbHRSpxizovJnfVGmbc0Q=,iv:FRqApt42I5q0y2wXT4PmkvIZSNakGyje8Q6gJlQ8Xto=,tag:0Rtgip0X2+tlR0Of83MLZA==,type:comment]
flightaware_feeder_id: ENC[AES256_GCM,data:2Z9M6ZpxyhzrUhXUvM/wL7p4xjD3oX8lXst07i4lzGCHrb9H,iv:7oWmTCaz2jpkxHaDMaJ2XWA9bRfHwivUSpbd+mwzExM=,tag:KSbj7d7vnNlJjzbAVvTcQQ==,type:str]
sops:
    lastmodified: "2026-08-20T14:15:27Z"
    mac: ENC[AES256_GCM,data:BBzmSv0s8wWO08WN3CeSXf4sePTSYIvcZWO6alWsnnRUDDIdiImyANm10ZnfbqbJVj9XaYvHzB944vGo6MFjmMX2TNmZu4bhJPtxlvT40adQHPNZDfXuUwawVCIgtRGc4MQjUFcGemZe6IVN7q093V1AFBcL52sGK4aaUSMizB4=,iv:WijJP/aYBfCPSo9lHq3gr01GAafMMTURbUuHm+HUv6Y=,tag:xNf4m25lGI27A4oNh7yuPw==,type:str]
    pgp:
        - created_at: "2026-08-20T14:14:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DB0GxLf1sGncSAQdA/nvQuC4RlgCc6LpQefxQetCEXxbJ03qW+dkUcW8k7Www
            TecmsH33NeKZeBh657whdlCmwAWEjN5Ut/cEgvX1bEqppgQVIT5iwGUwXZKLmwVF
            1GgBCQIQI/745ZLt1vf7N7utMC7Q0EqkBcUFLuR30K1smGFNhIjF7dtPrueOAY5H
            pcrc7tYB7e28Ig3/tngQH0Tix4v/HkXhWFqLyf6vpuTgC5CYOuflU//pumgLoc3t
            M8bbx3Yz6TGJww==
            =QR0/
            -----END PGP MESSAGE-----
          fp: 606BFCBC514F6C47F1E32AB31C9C80375373B4FD
    unencrypted_suffix: _unencrypted
    version: 3.13.1
