---
- name: raspberry pi
  hosts: raspberrypi
  become: true

  roles:
    - ibrahimmd.homelab.facts
    - ibrahimmd.raspberrypi.storage
    - ibrahimmd.homelab.plex

  tasks:
    - name: check ansible_user
      ansible.builtin.debug:
        msg: "ansible_user is {{ ansible_user }}"

